# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      solr:
        image: solr:9
        # options: -cloud -noprompt -f
        # command: bin/solr -cloud -noprompt -f
        ports:
          - "8983:8983"
      # postgres:
      #   image: postgres:11-alpine
      #   ports:
      #     - "5432:5432"
      #   env:
      #     POSTGRES_DB: rails_test
      #     POSTGRES_USER: rails
      #     POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      # Uncomment if we want to test on pg
      # DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
          ruby-version: 3.1
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Setup solr
        run: >
            cd solr/conf &&
            zip -1 -r solr_config.zip ./* &&
            curl -H "Content-type:application/octet-stream" --data-binary
            @solr_config.zip "http://localhost:8983/api/cluster/configs/solrconfig" &&
            curl "http://localhost:8983/api/cluster/configs?omitHeader=true" &&
            curl -H 'Content-type: application/json' http://localhost:8983/api/cores -d '{create: {name: blacklight-core, configSet: solrconfig}}'
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
          ruby-version: 3.1
      # Add or replace any other lints here
      # - name: Security audit dependencies
      #   run: bin/bundler-audit --update
      - name: Lint Ruby files
        run: bin/rubocop --parallel
